carts/urls.py
from django.urls import path 
from . import views

app_name = "carts"

urlpatterns = [
    path('carts_add/<slug:product_slug>/', views.carts_add, name='carts_add'),
    path('carts_change/<int:product_id>', views.carts_change, name = 'carts_change'),
    path('carts_change_plus/<int:product_id>', views.carts_change_plus, name = 'carts_change_plus'),
    path('carts_remove/<int:cart_id>/', views.carts_remove, name="carts_remove"),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path('', include("users.urls", namespace= 'users')),
    path('', include("goods.urls", namespace='goods')),
    path('', include("carts.urls", namespace='carts')),
]


from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

carts/models.py
from django.db import models
from goods.models import Products
from django.contrib.auth.models import User


class CartQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.product_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Пользователь",
    )
    product = models.ForeignKey(
        to=Products, on_delete=models.CASCADE, verbose_name="Продукт"
    )
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name="Количество")
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата добавления"
    )

    class Meta:
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"

    objects = CartQueryset().as_manager()

    def product_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Пользователь: {self.user.username} | Продукт: {self.product.name} | Количество: {self.quantity}"

carts/views.py
from django.shortcuts import redirect, render

from goods.models import Products
from carts.models import Cart

def carts_add(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user = request.user, product=product)
        
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user = request.user, product=product, quantity = 1)
    return redirect(request.META['HTTP_REFERER'])

def carts_change(request, product_id=None):
    
    cart_user = Cart.objects.get(id=product_id)
    print(cart_user.quantity)
    if request.user.is_authenticated:
        if cart_user.quantity > 0:
            cart_user.quantity -= 1
            print('res==', cart_user)
            cart_user.save()
    
    return redirect(request.META['HTTP_REFERER'])
    #return render(request, "carts/carts_change.html", context)

def carts_change_plus(request, product_id=None):
    
    cart_user = Cart.objects.get(id=product_id)
    print(cart_user.quantity)
    if request.user.is_authenticated:
        if cart_user.quantity >= 0:
            cart_user.quantity += 1
            print('res==', cart_user)
            cart_user.save()
    
    return redirect(request.META['HTTP_REFERER'])



def carts_remove(request, cart_id):
    cart = Cart.objects.get(id=cart_id)
    cart.delete()
    return redirect(request.META['HTTP_REFERER'])

carts/templates/carts/includes/included_cart.html
{% load carts_tags %}

{% user_carts request as carts %}
<h2 id="h2js">Корзина</h2>


{% for cart in carts %}
    <h3>{{cart.product.name}}</h3>

    
        {% csrf_token %}
        <a href='{% url "carts:carts_change" product_id=cart.id%}'style='width:30px;height:30px;border:1px solid black;text-decoration:none;padding: 0px 5px;'>-</a>
        <input type='text'value='{{cart.quantity}}'readonly style='width:50px;'id='input_cart'name='cart_quantity'>
        <a href='{% url "carts:carts_change_plus" product_id=cart.id%}'style='width:30px;height:30px;border:1px solid black;text-decoration:none;padding: 0px 5px;'>+</a>
    
    

    <p>{{cart.product.sell_price}} * {{cart.quantity}} = {{cart.product_price}}$</p>
    <p><a href='{% url "carts:carts_remove" cart.id%}'>Удалить товар из корзины</a></p>
    

    {% endfor %}
    <div class="">
        <p>И того:<strong>{{carts.total_quantity}}</strong>товар на сумму</p>
        <p>{{carts.total_price}} $</p>
    </div>
    {% if carts %}
        <div class="">
            <a href="#">Оформить заказ</a>
        </div>
    {% endif %}

   