carts/urls.py
from django.urls import path 
from . import views

app_name = "carts"

urlpatterns = [
    path('carts_add/<slug:product_slug>/', views.carts_add, name='carts_add'),
    path('carts_change/<int:product_id>', views.carts_change, name = 'carts_change'),
    path('carts_change_plus/<int:product_id>', views.carts_change_plus, name = 'carts_change_plus'),
    path('carts_remove/<int:cart_id>/', views.carts_remove, name="carts_remove"),
]

eshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path('', include("users.urls", namespace= 'users')),
    path('', include("goods.urls", namespace='goods')),
    path('', include("carts.urls", namespace='carts')),
]


from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name="search"),
    path('catalog/<slug:slug_cat>/', views.catalog, name="catalog"),
    path('product/<slug:prod_slug>/', views.product, name="product"),
]

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

goods/models.py
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=150, unique=True, verbose_name='URL')

    class Meta:
        verbose_name="Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name
    
class Products(models.Model):
    name = models.CharField(max_length = 150, unique=True, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to="images/",verbose_name='Изображение', blank=True, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name="Скидка")
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    slug = models.SlugField(blank=True, null=True, max_length=150, unique=True, verbose_name='URL')
    category = models.ForeignKey(Categories, on_delete = models.PROTECT, verbose_name='Категория')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = "Продукты"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100,2)
        return self.price

    def __str__(self):
        return self.name

goods/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from goods.models import Categories, Products
from django.core.paginator import Paginator
from goods.utils import search_goods

def catalog(request, slug_cat=None):
    page = request.GET.get("page",1)
    categ = Categories.objects.get(slug=slug_cat)
    #goods = Products.objects.filter(category = categ)
    query = request.GET.get('q', None)

    if slug_cat == 'all':
        goods = Products.objects.all()
    elif query:
        goods = search_goods(query)
    else:
        goods = Products.objects.filter(category = categ)
    

    order_by = request.GET.get('order_by', None)
    if order_by:
        goods = goods.order_by(order_by)

    discount = request.GET.get('discount')
    if discount:
        goods = goods.filter(discount__gt=0)

    paginator = Paginator(goods, 2)
    goods=paginator.page(int(page))


    context = {
        'categ':categ,
        #'prod_categ':prod_categ,
        'goods':goods,
        'slug_url':slug_cat,
        'paginator':paginator,
    }
    return render(request, "goods/catalog.html", context)

def product(request, prod_slug):
    prod = get_object_or_404(Products, slug=prod_slug)
    context = {
        'prod':prod,
    }
    return render(request, "goods/product.html", context)

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}

{% load catalog_tags %}

{% block content %}

<!--фильтрация товаров-->
<div class="form_filters">
    <form action=""method='get'>
        <input type="checkbox"class="input_filter"id='discount_goods'name='discount'value='discount'{%if request.GET.discount == 'discount' %}checked{%endif%}>
        <label for="discount_goods"class="label_input_filter">Товары по акции</label>
            
        <input type="radio"class="input_filter"id='order_by_goods'name='order_by'value="-price"{%if request.GET.order_by == '-price' %}checked{%endif%}>
        <label for="order_by_goods"class="label_input_filter">От дорогих к дешёвым</label>

        <input type="radio"class="input_filter"id='order_by_goods'name='order_by'value='price'{%if request.GET.order_by == 'price' %}checked{%endif%}>
        <label for="order_by_goods"class="label_input_filter">От дешёвых к дорогим</label>

        <button type='submit'>Применить</button>

    </form>
</div>
<div class="search">
    <!--Search-->
    <form action=""role="search"method='get'>
        <input type="search"id="search_product"name='q'>
        <button type="submit">Search</button>
    </form>
</div>

#Карточки товаров
<div class="products">
    <h2>{{categ.name}}</h2>
    <div class="products_catalog">
        {% for p in goods %}
            <div class="products_cart">
                <a href="{% url 'goods:product' prod_slug=p.slug %}">{{p.name}}</a>
                
                {% if p.image %}
                    <p><img src="{{p.image.url}}"alt='#'></p>
                {% else %}
                    <p><img src="{% static '/main/image/default.png' %}" alt=""></p>
                {% endif %}
                <p>{{p.description}}</p>
                <p>{{p.price}}</p>
                <p>{{p.discount}}%</p>
                <p>{{p.quantity}}шт</p>
                <p><a href="{% url "carts:carts_add" p.slug %}">Добавить товар в корзину</a></p>
            </div>
        {% endfor %}
    </div>
</div>


<div class="pagination">
    <span class="step-links">
        {% if goods.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ goods.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            
            {% for pag in goods.paginator.page_range %}
                {%comment%}<a href="?page={{p}}">{{p}}</a>{%endcomment%}
                <a href="?{% search_goods page=pag%}">{{pag}}</a>
            {%endfor%}
        </span>

        {% if goods.has_next %}
            <a href="?page={{ goods.next_page_number }}">next</a>
            <a href="?ppage={{goods.paginator.num_pages}}">last &raquo;</a>
        {% endif %}
    </span>
</div>
<p>{{request.GET.dict}}</p>

{% endblock content %}

goods/templates/goods/product.html
{% load static %}

<p>{{prod}}</p>
{% if prod.image %}
    <p><img src="{{prod.image.url}}"alt=""></p>
{% else %}
    <p><img src="{% static '/main/image/default.png' %}" alt=""></p>
{% endif %}
<p>{{prod.description}}</p>
<p>{{prod.price}}</p>
<p>{{prod.discount}}</p>
<p>{{prod.quantity}}</p>
<p><a href="{% url 'carts:carts_add' prod.slug %}">Добавить в корзину</a></p>