eshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path('', include("users.urls", namespace= 'users')),
    path('', include("goods.urls", namespace='goods')),
    path('', include("carts.urls", namespace='carts')),
]


from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('registration/', views.registration, name="registration"),
    path('profile/', views.profile, name="profile"),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout_user/', views.logout_user, name="logout_user"),
]

users/models.py
from django.db import models
#from django.contrib.auth.models import AbstractUser

# class User(AbstractUser):

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User 
        fields = ['username', 'password']

class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from users.forms import UserRegisterForm, UserLoginForm, UserProfileForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth
#from django.contrib.auth import authenticate


def login_user(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(request, username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect(reverse('users:profile'))
    else:
        form = UserLoginForm()
    context = {
        "form":form,

    }
    return render(request, "users/login_user.html", context)

def registration(request):
    if request.method == "POST":
        form = UserRegisterForm(data = request.POST)
        if form.is_valid():
            form.save()
            user=form.instance
            login(request, user)
            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = UserRegisterForm()
    context = {
        'form':form,
    }
    return render(request, "users/registration.html", context)
    

@login_required
def profile(request):
    if request.method == "POST":
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = UserProfileForm()
    context = {
        'form':form,
    }
    return render(request, "users/profile.html", context)

def users_cart(request):
    return render(request, "users/users_cart.html")

@login_required
def logout_user(request):
    logout(request)
    return redirect(reverse("main:index"))

users/templates/users/login_user.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<form action=" "method="post">
    {% csrf_token %}
   <input type="text"id='login_us'name='username'placeholder='Введите ваш логин'required>
    <label for="login_us">Введите логин</label>

    <input type="text"id='password_user'name='password'placeholder='Введите пароль'required>
    <label for="password_user">Введите пароль</label>

    --------------------------------

    <button type='submit'>Авторизоваться</button>
</form>

<p>Нет аккаунта?<a href='{% url "users:registration" %}'>Зарегистрируйтесь</a>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <form action=""method="post">
        {% csrf_token %}
        <input type="text"id='us_name'name='username'value='{{request.user.username}}'>
        <label for="us_name">Username</label>

        <input type="text"id='f_name'name='first_name'value="{% if request.user.first_name %}{{request.user.first_name}}{%else%}first_name{%endif%}">
        <label for="f_name">First_name</label>

        <input type="text"id='l_name'name='last_name'value=' {% if request.user.last_name %}{{request.user.last_name}}{%else%} last_name{%endif%}'>
        <label for="l_name">Last_name</label>

        <input type="email"id='email_user'name='email'value='{%if request.user.email%}{{request.user.email}}{%else%}email{%endif%}'>
        <label for="email_user">Email</label>
        <button type="submit">Обновить профиль</button>
    </form>
{% endblock content %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <form action=""method="post">
        {% csrf_token %}

        <input type="text"id='login'name='username'value='login'>
        <label for="login">Login</label>

        <input type="password"id="pass1"name='password1'value="password-1">
        <label for="pass1">Password</label>

        <input type="password"id="pass2"name='password2'value="password-2">
        <label for="pass2">Doble Password</label>

        <button type="submit">Зарегистрироваться</button>
    </form>

{% endblock content %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}

{%block content%}
    <div class='cart'style="background-color: #fff;">
        {%include "carts/includes/included_cart.html"%}
    </div>
    
{%endblock%}