eshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace='main')),
    path('', include("users.urls", namespace= 'users')),
    path('', include("goods.urls", namespace='goods')),
    path('', include("carts.urls", namespace='carts')),
]


from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path
from . import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name="search"),
    path('catalog/<slug:slug_cat>/', views.catalog, name="catalog"),
    path('product/<slug:prod_slug>/', views.product, name="product"),
]

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('registration/', views.registration, name="registration"),
    path('profile/', views.profile, name="profile"),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('logout_user/', views.logout_user, name="logout_user"),
]

templates/base.html
{% load static %}
{% load catalog_tags%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static './main/css/styles.css' %}">
</head>
<body>
    <div class="header">
        <div class='heading'>
            <h1>Eshop</h1>
        </div>
        <div class="menu">
            <ul>
                <li class='modal_catalog2'><a href="{% url 'main:index' %}"class='menu_a'>Главная</a></li>
                <li class='modal_catalog2'><a href="{% url 'main:about' %}"class='menu_a'>О нас</a></li>
                <li class='modal_catalog2'><a href="{% url "users:users_cart" %}"class='menu_a'>Корзина</a></li>
<!--<li><a href="#"class='menu_a'>Каталог</a></li>-->
                <li class="modal_catalog"id='mod_cat'>
                    <p onclick='mod()'id='but1'class='menu_b'>Каталог</p>
                    <p onclick='mod2()'id='but2'class='menu_b'>Каталог</p>
                    <div class='m_cat'id='m_cat'style='display:none;'>
                        {% tag_catalog as tcat %}
                        {% for cat_tag in tcat %}
                            <p><a href="{% url "goods:catalog" slug_cat=cat_tag.slug %}">{{cat_tag.name}}</a></p>
                        {% endfor %}
                    </div>
                </li>

                

                {% if not request.user.is_authenticated %}
                    <li id="lk"><a href="{% url "users:login_user" %}">Войти</a></li>
                {% else %}
                    <li id="lk"><a href="{% url "users:profile" %}">Личный кабинет</a> | <a href="{% url "users:logout_user" %}">Выйти</a></li>
                {% endif %}
            </ul>
        </div>
        {% block header %}
        {% endblock %}
    </div>
    <div class="sidebar">


        {% if request.user.is_staff and request.path == '/profile/' %}
            <a href="{% url 'admin:index' %}"target="_blank"style="margin-left:50px;">Admin</a>
        {% endif %}

        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        
        {% block footer %}
        {% endblock %}
    </div>

    <!--Модальнле окно Каталог-->
    {% comment %} <script>
        //document.getElementById('m_cat').onclick='mod';
        document.getElementById('but2').style.display='none';
        
        function mod() {
            document.getElementById('m_cat').style.display="block";
            document.getElementById('but2').style.display='block';
            document.getElementById('but1').style.display='none';
        }

        function mod2(){
            document.getElementById('m_cat').style.display="none";
            document.getElementById('but2').style.display='none';
            document.getElementById('but1').style.display='block';
        }
    </script> {% endcomment %}
    <script src="{% static './main/js/modal_catalog.js' %}"></script>
    <script src="{% static './main/js/styl.js' %}"></script>
</body>
</html>